version: '3.7'

services:

  e-commerce-demo:
    container_name: e-commerce-demo
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/e-commerce-demo
      - ./usr/src/e-commerce-demo/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

